### ISSUE TITLE
Daemonize? Export the database to file managers?

### ISSUE THREAD

**Issue by timofonic** [jvirkki/dupd#12]
Hello.

I find dupd quite interesting, specially because it uses a Sqlite database.

I have some questions...

- Why both file indexers and duplicated files finders aren't standarized into some kind of framework? There's:
* Gnome's [Tracker](https://wiki.gnome.org/Projects/Tracker).
* KDE's [Baloo](https://community.kde.org/Baloo)
* [Recoll](http://www.lesbonscomptes.com/recoll/).
* [ANGRYsearch](https://github.com/DoTheEvo/ANGRYsearch).
* [FSearch](https://github.com/cboxdoerfer/fsearch).
* [fzf](https://github.com/junegunn/fzf), 
* [SearchMonkey](http://searchmonkey.embeddediq.com/) (dead?).
* Unity Dash.

- Be daemonized and accept actions, updating or populating the database.
- Export or use the database with some file manager: Midnight Commander, Krusader, Thunar, Dolphin, emelFM2, GNOME Files, Caja, Nemo, PCManFM, ROX-Filer What about disk utilities like Filelight, Ncdu, dupeGuru, fslint... too?

Kind regards.

**Comment by jvirkki** [comment]
Exporting the duplicate data to other forms would be easy as it is already in an SQLite db. This could be done within dupd itself, or in companion scripts which access the same db file.

If there is a specific format you (or anyone else watching) would find useful, feel free to open an issue (or multiple issues, if multiple formats) with the specific details.

I'll close this one because it is so broad, but the general idea of exporting is good.

(dupd is called that, with the traditional daemon 'd' termination because initially I had planned on making it a daemon. In the end I decided not to go in that direction but the name stuck.)
