### ISSUE TITLE
Document third party dependencies before build

### ISSUE THREAD

**Issue by oliveox** [jvirkki/dupd#37]
I had to install a few dependencies before having 'make install' to work. 

**My suggestion:**

- Clearly list required dependencies so the user knows what to install before 'make install'.
- maybe a bash file that automatically installs them for each OS type

**My scenario**

OS: Ubuntu 20.4 

Ran 'make install'. Got: 

`In file included from src/test_hashlist.c:24:
src/hashlist.h:23:10: fatal error: sqlite3.h: No such file or directory
   23 | #include <sqlite3.h>
      |          ^~~~~~~~~~~
compilation terminated.
`

Solution

`sudo apt-get install libsqlite3-dev` 

Ran 'make install'. Error again:

`src/hash.c:36:10: fatal error: openssl/md5.h: No such file or directory
   36 | #include <openssl/md5.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.`

Solution:

`sudo apt-get install libpcap-dev libssl-dev`

'make install' successful.

**Comment by jvirkki** [comment]
The dependencies are documented in the BUILDING document.

How to install them will vary widely between platforms. I could include an example for Debian/Ubuntu since these are popular and stable, but don't want to start maintaining this for all platforms particularly the more unstable ones like OSX.
